name: altin-bot

on:
  schedule:
    - cron: "*/5 * * * *"   # 5 dakikada bir çalıştır
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu çek
      uses: actions/checkout@v3

    - name: Python kur
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Gerekli paketler
      run: |
        pip install requests pandas numpy

    - name: Botu çalıştır
      run: |
        python altin.py

    - name: Logları kaydet ve push et
      run: |
        echo "Çalışma zamanı: $(date)" >> bot_log.txt

        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions[bot]"

        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}

        git add bot_log.txt
        git commit -m "Bot log güncellendi" || echo "Commit yok"
        git push origin HEAD:${{ github.ref }}
